plugins:
  hooks_plugin:
    executor: central_deployment_agent
    package_name: cloudify-hooks-plugin
    package_version: '1.0.0'

workflows:

  workflow_failed:
    mapping: hooks_plugin.cloudify_hooks.tasks.workflow_failed
    parameters: {}
